data_ingestion:
  test_size: 0.2    # 20% data for test set

feature_engineering:
  max_features: 10  # Select top 10 features

model_building:
  n_estimators: 100  # Number of trees in RandomForest
  random_state: 42   # Seed for reproducibility
